#!/bin/sh

set -e

case "${1}" in
  configure)
    update-mime-database /usr/share/mime
    gtk-update-icon-cache /usr/share/icons/hicolor/
    ln -sf /usr/lib/scratch3/scratch-desktop /usr/bin/scratch3
    ;;

  abort-upgrade|abort-remove|abort-deconfigure)

    ;;

  *)
    echo "postinst called with unknown argument \`${1}'" >&2
    exit 1
    ;;
esac


